### ISSUE TITLE
dev doesn't work

### ISSUE THREAD

**Issue by lorvent** [FriendlyUser/vuepress-theme-cool#18]
**Describe the bug**
Build working fine but when i run `npm run docs:dev` then it throws console errors and blank page

**To Reproduce**
run `npm run docs:dev`

**Expected behavior**
it should run dev server without any errors.

**Comment by FriendlyUser** [comment]
I'll look into this, can you please provide the version of `vuepress` and `vuepress-theme-cool` (I assume it is the latest for `vuepress`

If you have vuepress installed globally then `npm run dev` should work, otherwise if you want to install different versions of vuepress per repo under `node_modules` in your project folder then run `npm run docs:dev`.


`npm run dev` runs off the global vuepress instance and `npm run dev:docs`  runs the vuepress installed for the local project.

I believe by default the `vuepress-cool-theme-starter` repo is expecting vuepress to be installed globally.

Perhaps this is just a poor documentation issue.

**Comment by lorvent** [comment]
Hello,

thanks for the fast response.

`vuepress` version is latest, same with `vuepress-theme-cool` too (1.3.1)

i have vuepress installed globally and i tried running `vuepress dev docs`, `npm run dev` and `yarn run dev` like that, looking at all commands available in `package.json`

on stock, vuepress, `vuepress dev docs` works just fine.

thanks.

**Comment by awehrung-datev** [comment]
Hi,

I might be too dumb but I don't get it to run, and it seems to be the same problem, that's why I'm commenting here. I also have `"vuepress": "^1.7.1",  "vuepress-theme-cool": "^1.3.1"` installed, but both commands fail to render the pages. Only the favicon gets displayed correctly in the tab bar.

What am I missing? Thanks in advance.

PS: I can open a new issue if you prefer

**Comment by FriendlyUser** [comment]
See #20
