### ISSUE TITLE
Plantuml stopped working for 1.0.3 beta version

### ISSUE THREAD

**Issue by chbndrhnns** [FriendlyUser/vuepress-theme-cool#9]
If I use your 1.0.3 beta version, I see the plain PlantUML code instead of a rendered diagram.

**Comment by FriendlyUser** [comment]
```
 markdown: {
    extendMarkdown: md => {
      md.set({ html: true })
      md.use(require('markdown-it-katex'))
      md.use(require('markdown-it-plantuml'))
      md.use(require('markdown-it-admonition'))
    }
  }
```

Vuepress 1 changed the way you improve markdown-it-extensions,, https://v1.vuepress.vuejs.org/miscellaneous/migration-guide.html#markdown-config and https://v1.vuepress.vuejs.org/config/#markdown-extendmarkdown, since it displays correctly on thevuepress-theme-cool-starter site, I think this is an configuration issue

**Comment by chbndrhnns** [comment]
You are correct. I did not apply the updated settings. Thanks so much for the help!
